<?php

namespace Database\Seeders;

use App\Models\TechnicalSkill;
use Illuminate\Database\Seeder;

class TechnicalSkillsSeeder extends Seeder
{
    public function run(): void
    {
        $skills = [

            // ====================== BACKEND ======================
            // Lenguajes, frameworks y herramientas del lado del servidor

            ['name' => 'Actix',          'category' => 'Backend', 'icon_path' => 'iconskills/Actix-Light.svg'],
            ['name' => 'Adonis',         'category' => 'Backend', 'icon_path' => 'iconskills/Adonis.svg'],
            ['name' => 'Apollo',         'category' => 'Backend', 'icon_path' => 'iconskills/Apollo.svg'],
            ['name' => 'Appwrite',       'category' => 'Backend', 'icon_path' => 'iconskills/Appwrite.svg'],
            ['name' => 'Django',         'category' => 'Backend', 'icon_path' => 'iconskills/Django.svg'],
            ['name' => 'DotNet',         'category' => 'Backend', 'icon_path' => 'iconskills/DotNet.svg'],
            ['name' => 'Elixir',         'category' => 'Backend', 'icon_path' => 'iconskills/Elixir-Light.svg'],
            ['name' => 'ExpressJS',      'category' => 'Backend', 'icon_path' => 'iconskills/ExpressJS-Light.svg'],
            ['name' => 'FastAPI',        'category' => 'Backend', 'icon_path' => 'iconskills/FastAPI.svg'],
            ['name' => 'Flask',          'category' => 'Backend', 'icon_path' => 'iconskills/Flask-Light.svg'],
            ['name' => 'GoLang',         'category' => 'Backend', 'icon_path' => 'iconskills/GoLang.svg'],
            ['name' => 'Java',           'category' => 'Backend', 'icon_path' => 'iconskills/Java-Light.svg'],
            ['name' => 'Kotlin',         'category' => 'Backend', 'icon_path' => 'iconskills/Kotlin-Light.svg'],
            ['name' => 'Ktor',           'category' => 'Backend', 'icon_path' => 'iconskills/Ktor-Light.svg'],
            ['name' => 'Laravel',        'category' => 'Backend', 'icon_path' => 'iconskills/Laravel-Light.svg'],
            ['name' => 'NestJS',         'category' => 'Backend', 'icon_path' => 'iconskills/NestJS-Light.svg'],
            ['name' => 'NodeJS',         'category' => 'Backend', 'icon_path' => 'iconskills/NodeJS-Light.svg'],
            ['name' => 'PHP',            'category' => 'Backend', 'icon_path' => 'iconskills/PHP-Light.svg'],
            ['name' => 'Prisma',         'category' => 'Backend', 'icon_path' => 'iconskills/Prisma.svg'],
            ['name' => 'Python',         'category' => 'Backend', 'icon_path' => 'iconskills/Python-Light.svg'],
            ['name' => 'Rails',          'category' => 'Backend', 'icon_path' => 'iconskills/Rails.svg'],
            ['name' => 'Ruby',           'category' => 'Backend', 'icon_path' => 'iconskills/Ruby.svg'],
            ['name' => 'Rust',           'category' => 'Backend', 'icon_path' => 'iconskills/Rust.svg'],
            ['name' => 'Spring',         'category' => 'Backend', 'icon_path' => 'iconskills/Spring-Light.svg'],
            ['name' => 'Symfony',        'category' => 'Backend', 'icon_path' => 'iconskills/Symfony-Light.svg'],
            ['name' => 'ActivityPub',      'category' => 'Backend', 'icon_path' => 'iconskills/ActivityPub-Light.svg'],
            ['name' => 'Bun',              'category' => 'Backend', 'icon_path' => 'iconskills/Bun-Light.svg'],
            ['name' => 'Deno',             'category' => 'Backend', 'icon_path' => 'iconskills/DENO-Light.svg'],
            ['name' => 'Elysia',           'category' => 'Backend', 'icon_path' => 'iconskills/Elysia-Light.svg'],
            ['name' => 'Bevy',             'category' => 'Backend', 'icon_path' => 'iconskills/Bevy-Light.svg'],
            ['name' => 'Cassandra',        'category' => 'Backend', 'icon_path' => 'iconskills/Cassandra-Light.svg'],
            ['name' => 'DynamoDB',         'category' => 'Backend', 'icon_path' => 'iconskills/DynamoDB-Light.svg'],
            ['name' => 'Elasticsearch',    'category' => 'Backend', 'icon_path' => 'iconskills/Elasticsearch-Light.svg'],
            ['name' => 'GraphQL',          'category' => 'Backend', 'icon_path' => 'iconskills/GraphQL-Light.svg'],
            ['name' => 'Kafka',            'category' => 'Backend', 'icon_path' => 'iconskills/Kafka.svg'],
            ['name' => 'RabbitMQ',         'category' => 'Backend', 'icon_path' => 'iconskills/RabbitMQ-Light.svg'],
            ['name' => 'Sequelize',        'category' => 'Backend', 'icon_path' => 'iconskills/Sequelize-Light.svg'],
            ['name' => 'Supabase',         'category' => 'Backend', 'icon_path' => 'iconskills/Supabase-Light.svg'],
            ['name' => 'OpenShift',        'category' => 'Backend', 'icon_path' => 'iconskills/OpenShift.svg'],
            ['name' => 'OpenStack',        'category' => 'Backend', 'icon_path' => 'iconskills/OpenStack-Light.svg'],
            ['name' => 'AiScript',         'category' => 'Backend', 'icon_path' => 'iconskills/AiScript-Light.svg'],
            ['name' => 'DiscordJS',        'category' => 'Backend', 'icon_path' => 'iconskills/DiscordJS-Light.svg'],
            ['name' => 'Julia',            'category' => 'Backend', 'icon_path' => 'iconskills/Julia-Light.svg'],
            ['name' => 'PyTorch',        'category' => 'Backend', 'icon_path' => 'iconskills/PyTorch-Light.svg'],
            ['name' => 'QT',             'category' => 'Backend', 'icon_path' => 'iconskills/QT-Light.svg'],
            ['name' => 'ROS',            'category' => 'Backend', 'icon_path' => 'iconskills/ROS-Light.svg'],
            ['name' => 'TensorFlow',     'category' => 'Backend', 'icon_path' => 'iconskills/TensorFlow-Light.svg'],
            ['name' => 'Zig',            'category' => 'Backend', 'icon_path' => 'iconskills/Zig-Light.svg'],
            ['name' => 'Clojure',          'category' => 'Backend', 'icon_path' => 'iconskills/Clojure-Light.svg'],
            ['name' => 'CMake',            'category' => 'Backend', 'icon_path' => 'iconskills/CMake-Light.svg'],
            ['name' => 'Crystal',          'category' => 'Backend', 'icon_path' => 'iconskills/Crystal-Light.svg'],
            ['name' => 'Vala',             'category' => 'Backend', 'icon_path' => 'iconskills/Vala.svg'],
            ['name' => 'V',                'category' => 'Backend', 'icon_path' => 'iconskills/V-Light.svg'],
            ['name' => 'Verilog',          'category' => 'Backend', 'icon_path' => 'iconskills/Verilog.svg'],
            ['name' => 'Fortran',       'category' => 'Backend', 'icon_path' => 'iconskills/Fortran.svg'],
            ['name' => 'Forth',       'category' => 'Backend', 'icon_path' => 'iconskills/Forth.svg'],
            ['name' => 'Haskell',       'category' => 'Backend', 'icon_path' => 'iconskills/Haskell-Light.svg'],
            ['name' => 'Lua',        'category' => 'Backend', 'icon_path' => 'iconskills/Lua-Light.svg'],
            ['name' => 'Matlab',        'category' => 'Backend', 'icon_path' => 'iconskills/Matlab-Light.svg'],
            ['name' => 'OCaml',         'category' => 'Backend', 'icon_path' => 'iconskills/OCaml.svg'],
            ['name' => 'Octave',        'category' => 'Backend', 'icon_path' => 'iconskills/Octave-Light.svg'],
            ['name' => 'OpenCV',        'category' => 'Backend', 'icon_path' => 'iconskills/OpenCV-Light.svg'],
            ['name' => 'Perl',      'category' => 'Backend', 'icon_path' => 'iconskills/Perl.svg'],
            ['name' => 'RubyMotion', 'category' => 'Backend', 'icon_path' => 'iconskills/Ruby.svg'],
            ['name' => 'Scala',         'category' => 'Backend', 'icon_path' => 'iconskills/Scala-Light.svg'],
            ['name' => 'Selenium',      'category' => 'Backend', 'icon_path' => 'iconskills/Selenium.svg'],
            ['name' => 'Solidity',  'category' => 'Backend', 'icon_path' => 'iconskills/Solidity.svg'],
            ['name' => 'Swift',     'category' => 'Backend', 'icon_path' => 'iconskills/Swift.svg'],
            ['name' => 'Hibernate',     'category' => 'Backend', 'icon_path' => 'iconskills/Hibernate-Light.svg'],

            // ====================== FRONTEND ======================
            // Frameworks, librerías y herramientas de interfaz de usuario

            ['name' => 'AlpineJS',       'category' => 'Frontend', 'icon_path' => 'iconskills/AlpineJS-Light.svg'],
            ['name' => 'Angular',        'category' => 'Frontend', 'icon_path' => 'iconskills/Angular-Light.svg'],
            ['name' => 'Astro',          'category' => 'Frontend', 'icon_path' => 'iconskills/Astro.svg'],
            ['name' => 'Bootstrap',      'category' => 'Frontend', 'icon_path' => 'iconskills/Bootstrap.svg'],
            ['name' => 'CSS',            'category' => 'Frontend', 'icon_path' => 'iconskills/CSS.svg'],
            ['name' => 'Electron',       'category' => 'Frontend', 'icon_path' => 'iconskills/Electron.svg'],
            ['name' => 'Ember',          'category' => 'Frontend', 'icon_path' => 'iconskills/Ember.svg'],
            ['name' => 'Figma',          'category' => 'Frontend', 'icon_path' => 'iconskills/Figma-Light.svg'],
            ['name' => 'Flutter',        'category' => 'Frontend', 'icon_path' => 'iconskills/Flutter-Light.svg'],
            ['name' => 'Gatsby',         'category' => 'Frontend', 'icon_path' => 'iconskills/Gatsby.svg'],
            ['name' => 'HTML',           'category' => 'Frontend', 'icon_path' => 'iconskills/HTML.svg'],
            ['name' => 'Htmx',           'category' => 'Frontend', 'icon_path' => 'iconskills/Htmx-Light.svg'],
            ['name' => 'JavaScript',     'category' => 'Frontend', 'icon_path' => 'iconskills/JavaScript.svg'],
            ['name' => 'JQuery',         'category' => 'Frontend', 'icon_path' => 'iconskills/JQuery.svg'],
            ['name' => 'Lit',            'category' => 'Frontend', 'icon_path' => 'iconskills/Lit-Light.svg'],
            ['name' => 'MaterialUI',     'category' => 'Frontend', 'icon_path' => 'iconskills/MaterialUI-Light.svg'],
            ['name' => 'NextJS',         'category' => 'Frontend', 'icon_path' => 'iconskills/NextJS-Light.svg'],
            ['name' => 'NuxtJS',         'category' => 'Frontend', 'icon_path' => 'iconskills/NuxtJS-Light.svg'],
            ['name' => 'Pinia',          'category' => 'Frontend', 'icon_path' => 'iconskills/Pinia-Light.svg'],
            ['name' => 'React',          'category' => 'Frontend', 'icon_path' => 'iconskills/React-Light.svg'],
            ['name' => 'Redux',          'category' => 'Frontend', 'icon_path' => 'iconskills/Redux.svg'],
            ['name' => 'Remix',          'category' => 'Frontend', 'icon_path' => 'iconskills/Remix-Light.svg'],
            ['name' => 'Sass',           'category' => 'Frontend', 'icon_path' => 'iconskills/Sass.svg'],
            ['name' => 'SolidJS',        'category' => 'Frontend', 'icon_path' => 'iconskills/SolidJS-Light.svg'],
            ['name' => 'StyledComponents', 'category' => 'Frontend', 'icon_path' => 'iconskills/StyledComponents.svg'],
            ['name' => 'Svelte',         'category' => 'Frontend', 'icon_path' => 'iconskills/Svelte.svg'],
            ['name' => 'TailwindCSS',    'category' => 'Frontend', 'icon_path' => 'iconskills/TailwindCSS-Light.svg'],
            ['name' => 'ThreeJS',        'category' => 'Frontend', 'icon_path' => 'iconskills/ThreeJS-Light.svg'],
            ['name' => 'TypeScript',     'category' => 'Frontend', 'icon_path' => 'iconskills/TypeScript.svg'],
            ['name' => 'VueJS',          'category' => 'Frontend', 'icon_path' => 'iconskills/VueJS-Light.svg'],
            ['name' => 'Vuetify',        'category' => 'Frontend', 'icon_path' => 'iconskills/Vuetify-Light.svg'],
            ['name' => 'Vite',           'category' => 'Frontend', 'icon_path' => 'iconskills/Vite-Light.svg'],
            ['name' => 'Webflow',        'category' => 'Frontend', 'icon_path' => 'iconskills/Webflow.svg'],
            ['name' => 'Webpack',        'category' => 'Frontend', 'icon_path' => 'iconskills/Webpack-Light.svg'],
            ['name' => 'D3JS',             'category' => 'Frontend', 'icon_path' => 'iconskills/D3-Light.svg'],
            ['name' => 'Cypress',          'category' => 'Frontend', 'icon_path' => 'iconskills/Cypress-Light.svg'],
            ['name' => 'Emotion',          'category' => 'Frontend', 'icon_path' => 'iconskills/Emotion-Light.svg'],
            ['name' => 'Pug',              'category' => 'Frontend', 'icon_path' => 'iconskills/Pug-Light.svg'],
            ['name' => 'Processing',       'category' => 'Frontend', 'icon_path' => 'iconskills/Processing-Light.svg'],
            ['name' => 'RollupJS',         'category' => 'Frontend', 'icon_path' => 'iconskills/RollupJS-Light.svg'],
            ['name' => 'ReactQuery',       'category' => 'Frontend', 'icon_path' => 'iconskills/ReactiveX-Light.svg'],
            ['name' => 'Tauri',            'category' => 'Frontend', 'icon_path' => 'iconskills/Tauri-Light.svg'],
            ['name' => 'WindiCSS',         'category' => 'Frontend', 'icon_path' => 'iconskills/WindiCSS-Light.svg'],
            ['name' => 'WebAssembly',      'category' => 'Frontend', 'icon_path' => 'iconskills/WebAssembly.svg'],
            ['name' => 'Yew',              'category' => 'Frontend', 'icon_path' => 'iconskills/Yew-Light.svg'],
            ['name' => 'Less',           'category' => 'Frontend', 'icon_path' => 'iconskills/Less-Light.svg'],
            ['name' => 'Yarn',           'category' => 'Frontend', 'icon_path' => 'iconskills/Yarn-Light.svg'],
            ['name' => 'CodePen',          'category' => 'Frontend', 'icon_path' => 'iconskills/CodePen-Light.svg'],
            ['name' => 'CoffeeScript',     'category' => 'Frontend', 'icon_path' => 'iconskills/CoffeeScript-Light.svg'],
            ['name' => 'P5JS',             'category' => 'Frontend', 'icon_path' => 'iconskills/p5js.svg'],
            ['name' => 'Markdown',         'category' => 'Frontend', 'icon_path' => 'iconskills/Markdown-Light.svg'],
            ['name' => 'Gulp',             'category' => 'Frontend', 'icon_path' => 'iconskills/Gulp.svg'],

            // ====================== DEVOPS ======================
            // Herramientas de infraestructura, CI/CD, contenedores y cloud

            ['name' => 'Ansible',        'category' => 'DevOps', 'icon_path' => 'iconskills/Ansible.svg'],
            ['name' => 'AWS',            'category' => 'DevOps', 'icon_path' => 'iconskills/AWS-Light.svg'],
            ['name' => 'Azure',          'category' => 'DevOps', 'icon_path' => 'iconskills/Azure-Light.svg'],
            ['name' => 'Cloudflare',     'category' => 'DevOps', 'icon_path' => 'iconskills/Cloudflare-Light.svg'],
            ['name' => 'Docker',         'category' => 'DevOps', 'icon_path' => 'iconskills/Docker.svg'],
            ['name' => 'GCP',            'category' => 'DevOps', 'icon_path' => 'iconskills/GCP-Light.svg'],
            ['name' => 'GithubActions',  'category' => 'DevOps', 'icon_path' => 'iconskills/GithubActions-Light.svg'],
            ['name' => 'GitLab',         'category' => 'DevOps', 'icon_path' => 'iconskills/GitLab-Light.svg'],
            ['name' => 'Grafana',        'category' => 'DevOps', 'icon_path' => 'iconskills/Grafana-Light.svg'],
            ['name' => 'Heroku',         'category' => 'DevOps', 'icon_path' => 'iconskills/Heroku.svg'],
            ['name' => 'Jenkins',        'category' => 'DevOps', 'icon_path' => 'iconskills/Jenkins-Light.svg'],
            ['name' => 'Kubernetes',     'category' => 'DevOps', 'icon_path' => 'iconskills/Kubernetes.svg'],
            ['name' => 'Netlify',        'category' => 'DevOps', 'icon_path' => 'iconskills/Netlify-Light.svg'],
            ['name' => 'Nginx',          'category' => 'DevOps', 'icon_path' => 'iconskills/Nginx.svg'],
            ['name' => 'Prometheus',     'category' => 'DevOps', 'icon_path' => 'iconskills/Prometheus.svg'],
            ['name' => 'Terraform',      'category' => 'DevOps', 'icon_path' => 'iconskills/Terraform-Light.svg'],
            ['name' => 'Vercel',         'category' => 'DevOps', 'icon_path' => 'iconskills/Vercel-Light.svg'],
            ['name' => 'BitBucket',        'category' => 'DevOps', 'icon_path' => 'iconskills/BitBucket-Light.svg'],
            ['name' => 'GitHub',           'category' => 'DevOps', 'icon_path' => 'iconskills/Github-Light.svg'],
            ['name' => 'GitLabCI',         'category' => 'DevOps', 'icon_path' => 'iconskills/GitLab-Light.svg'],
            ['name' => 'Gradle',           'category' => 'DevOps', 'icon_path' => 'iconskills/Gradle-Light.svg'],
            ['name' => 'Maven',            'category' => 'DevOps', 'icon_path' => 'iconskills/Maven-Light.svg'],
            ['name' => 'PrometheusStack',  'category' => 'DevOps', 'icon_path' => 'iconskills/Prometheus.svg'],
            ['name' => 'Sentry',           'category' => 'DevOps', 'icon_path' => 'iconskills/Sentry.svg'],
            ['name' => 'Vim',              'category' => 'DevOps', 'icon_path' => 'iconskills/VIM-Light.svg'],
            ['name' => 'VSCodium',         'category' => 'DevOps', 'icon_path' => 'iconskills/VSCodium-Light.svg'],
            ['name' => 'WebStorm',         'category' => 'DevOps', 'icon_path' => 'iconskills/WebStorm-Light.svg'],
            ['name' => 'PlanetScale',     'category' => 'DevOps', 'icon_path' => 'iconskills/PlanetScale-Light.svg'],
            ['name' => 'Powershell',      'category' => 'DevOps', 'icon_path' => 'iconskills/Powershell-Light.svg'],
            ['name' => 'VIM',              'category' => 'DevOps', 'icon_path' => 'iconskills/VIM-Light.svg'],
            ['name' => 'VisualStudio',     'category' => 'DevOps', 'icon_path' => 'iconskills/VisualStudio-Light.svg'],
            ['name' => 'SublimeText',      'category' => 'DevOps', 'icon_path' => 'iconskills/Sublime-Light.svg'],
            ['name' => 'Rider',            'category' => 'DevOps', 'icon_path' => 'iconskills/Rider-Light.svg'],
            ['name' => 'PyCharm',          'category' => 'DevOps', 'icon_path' => 'iconskills/PyCharm-Light.svg'],
            ['name' => 'PhpStorm',         'category' => 'DevOps', 'icon_path' => 'iconskills/PhpStorm-Light.svg'],
            ['name' => 'Postman',          'category' => 'DevOps', 'icon_path' => 'iconskills/Postman.svg'],
            ['name' => 'Emacs',            'category' => 'DevOps', 'icon_path' => 'iconskills/Emacs.svg'],
            // ====================== OTROS ======================
            // Bases de datos, editores, sistemas operativos, herramientas de diseño,
            // testing, game dev, IA/ML, etc.

            ['name' => 'AndroidStudio',  'category' => 'Otros', 'icon_path' => 'iconskills/AndroidStudio-Light.svg'],
            ['name' => 'Arduino',        'category' => 'Otros', 'icon_path' => 'iconskills/Arduino.svg'],
            ['name' => 'Bash',           'category' => 'Otros', 'icon_path' => 'iconskills/Bash-Light.svg'],
            ['name' => 'Blender',        'category' => 'Otros', 'icon_path' => 'iconskills/Blender-Light.svg'],
            ['name' => 'C',              'category' => 'Otros', 'icon_path' => 'iconskills/C.svg'],
            ['name' => 'CPP',            'category' => 'Otros', 'icon_path' => 'iconskills/CPP.svg'],
            ['name' => 'CSharp',         'category' => 'Otros', 'icon_path' => 'iconskills/CS.svg'],
            ['name' => 'Dart',           'category' => 'Otros', 'icon_path' => 'iconskills/Dart-Light.svg'],
            ['name' => 'Firebase',       'category' => 'Otros', 'icon_path' => 'iconskills/Firebase-Light.svg'],
            ['name' => 'Git',            'category' => 'Otros', 'icon_path' => 'iconskills/Git.svg'],
            ['name' => 'Godot',          'category' => 'Otros', 'icon_path' => 'iconskills/Godot-Light.svg'],
            ['name' => 'Illustrator',    'category' => 'Otros', 'icon_path' => 'iconskills/Illustrator.svg'],
            ['name' => 'Linux',          'category' => 'Otros', 'icon_path' => 'iconskills/Linux-Light.svg'],
            ['name' => 'MongoDB',        'category' => 'Otros', 'icon_path' => 'iconskills/MongoDB.svg'],
            ['name' => 'MySQL',          'category' => 'Otros', 'icon_path' => 'iconskills/MySQL-Light.svg'],
            ['name' => 'NeoVim',         'category' => 'Otros', 'icon_path' => 'iconskills/NeoVim-Light.svg'],
            ['name' => 'Photoshop',      'category' => 'Otros', 'icon_path' => 'iconskills/Photoshop.svg'],
            ['name' => 'PostgreSQL',     'category' => 'Otros', 'icon_path' => 'iconskills/PostgreSQL-Light.svg'],
            ['name' => 'Redis',          'category' => 'Otros', 'icon_path' => 'iconskills/Redis-Light.svg'],
            ['name' => 'SQLite',         'category' => 'Otros', 'icon_path' => 'iconskills/SQLite.svg'],
            ['name' => 'Unity',          'category' => 'Otros', 'icon_path' => 'iconskills/Unity-Light.svg'],
            ['name' => 'UnrealEngine',   'category' => 'Otros', 'icon_path' => 'iconskills/UnrealEngine.svg'],
            ['name' => 'VSCode',         'category' => 'Otros', 'icon_path' => 'iconskills/VSCode-Light.svg'],
            ['name' => 'Windows',        'category' => 'Otros', 'icon_path' => 'iconskills/Windows-Light.svg'],
            ['name' => 'AfterEffects',     'category' => 'Otros', 'icon_path' => 'iconskills/AfterEffects.svg'],
            ['name' => 'Anaconda',         'category' => 'Otros', 'icon_path' => 'iconskills/Anaconda-Light.svg'],
            ['name' => 'Apple',            'category' => 'Otros', 'icon_path' => 'iconskills/Apple-Light.svg'],
            ['name' => 'ArchLinux',        'category' => 'Otros', 'icon_path' => 'iconskills/Arch-Light.svg'],
            ['name' => 'Atom',             'category' => 'Otros', 'icon_path' => 'iconskills/Atom.svg'],
            ['name' => 'Audition',         'category' => 'Otros', 'icon_path' => 'iconskills/Audition.svg'],
            ['name' => 'AutoCAD',          'category' => 'Otros', 'icon_path' => 'iconskills/AutoCAD-Light.svg'],
            ['name' => 'BSD',              'category' => 'Otros', 'icon_path' => 'iconskills/BSD-Light.svg'],
            ['name' => 'CLion',            'category' => 'Otros', 'icon_path' => 'iconskills/CLion-Light.svg'],
            ['name' => 'Debian',           'category' => 'Otros', 'icon_path' => 'iconskills/Debian-Light.svg'],
            ['name' => 'Discord',          'category' => 'Otros', 'icon_path' => 'iconskills/Discord.svg'],
            ['name' => 'Eclipse',          'category' => 'Otros', 'icon_path' => 'iconskills/Eclipse-Light.svg'],
            ['name' => 'Fediverse',        'category' => 'Otros', 'icon_path' => 'iconskills/Fediverse-Light.svg'],
            ['name' => 'Gmail',            'category' => 'Otros', 'icon_path' => 'iconskills/Gmail-Light.svg'],
            ['name' => 'KaliLinux',        'category' => 'Otros', 'icon_path' => 'iconskills/Kali-Light.svg'],
            ['name' => 'LinkedIn',         'category' => 'Otros', 'icon_path' => 'iconskills/LinkedIn.svg'],
            ['name' => 'Mastodon',         'category' => 'Otros', 'icon_path' => 'iconskills/Mastodon-Light.svg'],
            ['name' => 'Mint',             'category' => 'Otros', 'icon_path' => 'iconskills/Mint-Light.svg'],
            ['name' => 'Misskey',          'category' => 'Otros', 'icon_path' => 'iconskills/Misskey-Light.svg'],
            ['name' => 'Premiere',         'category' => 'Otros', 'icon_path' => 'iconskills/Premiere.svg'],
            ['name' => 'RaspberryPi',      'category' => 'Otros', 'icon_path' => 'iconskills/RaspberryPi-Light.svg'],
            ['name' => 'Sketchup',         'category' => 'Otros', 'icon_path' => 'iconskills/Sketchup-Light.svg'],
            ['name' => 'Spotify',          'category' => 'Otros', 'icon_path' => 'iconskills/Spotify-Light.svg'],
            ['name' => 'StackOverflow',    'category' => 'Otros', 'icon_path' => 'iconskills/StackOverflow-Light.svg'],
            ['name' => 'Ubuntu',           'category' => 'Otros', 'icon_path' => 'iconskills/Ubuntu-Light.svg'],
            ['name' => 'Ableton',          'category' => 'Otros', 'icon_path' => 'iconskills/Ableto-Light.svg'],
            ['name' => 'DevTo',           'category' => 'Otros', 'icon_path' => 'iconskills/DevTo-Light.svg'],
            ['name' => 'Obsidian',        'category' => 'Otros', 'icon_path' => 'iconskills/Obsidian-Light.svg'],
            ['name' => 'Gherkin',       'category' => 'Otros', 'icon_path' => 'iconskills/Gherkin-Light.svg'],
            ['name' => 'GTK',           'category' => 'Otros', 'icon_path' => 'iconskills/GTK-Light.svg'],
            ['name' => 'Haxe',          'category' => 'Otros', 'icon_path' => 'iconskills/Haxe-Light.svg'],
            ['name' => 'HaxeFlixel',    'category' => 'Otros', 'icon_path' => 'iconskills/HaxeFlixel-Light.svg'],
            ['name' => 'Idea',          'category' => 'Otros', 'icon_path' => 'iconskills/Idea-Light.svg'],
            ['name' => 'IPFS',          'category' => 'Otros', 'icon_path' => 'iconskills/IPFS-Light.svg'],
            ['name' => 'LaTeX',         'category' => 'Otros', 'icon_path' => 'iconskills/LaTeX-Light.svg'],
            ['name' => 'Nim',           'category' => 'Otros', 'icon_path' => 'iconskills/Nim-Light.svg'],
            ['name' => 'Nix',           'category' => 'Otros', 'icon_path' => 'iconskills/Nix-Light.svg'],
            ['name' => 'Notion',        'category' => 'Otros', 'icon_path' => 'iconskills/Notion-Light.svg'],
            ['name' => 'Npm',           'category' => 'Otros', 'icon_path' => 'iconskills/Npm-Light.svg'],
            ['name' => 'Pkl',           'category' => 'Otros', 'icon_path' => 'iconskills/Pkl-Light.svg'],
            ['name' => 'Plan9',         'category' => 'Otros', 'icon_path' => 'iconskills/Plan9-Light.svg'],
            ['name' => 'Pnpm',          'category' => 'Otros', 'icon_path' => 'iconskills/Pnpm-Light.svg'],
            ['name' => 'R',             'category' => 'Otros', 'icon_path' => 'iconskills/R-Light.svg'],
            ['name' => 'RedHat',        'category' => 'Otros', 'icon_path' => 'iconskills/RedHat-Light.svg'],
            ['name' => 'Regex',         'category' => 'Otros', 'icon_path' => 'iconskills/Regex-Light.svg'],
            ['name' => 'Replit',        'category' => 'Otros', 'icon_path' => 'iconskills/Replit-Light.svg'],
            ['name' => 'SciKitLearn',   'category' => 'Otros', 'icon_path' => 'iconskills/SciKitLearn-Light.svg'],
            ['name' => 'SVG',           'category' => 'Otros', 'icon_path' => 'iconskills/SVG-Light.svg'],
            ['name' => 'Vitest',        'category' => 'Otros', 'icon_path' => 'iconskills/Vitest-Light.svg'],
            ['name' => 'Workers',       'category' => 'Otros', 'icon_path' => 'iconskills/Workers-Light.svg'],
            // ... (puedes seguir agregando los que faltan aquí)

        ];

        foreach ($skills as $skill) {
            TechnicalSkill::firstOrCreate(
                ['icon_path' => $skill['icon_path']],
                [
                    'name' => $skill['name'],
                    'category' => $skill['category'],
                ]
            );
        }

        $this->command->info('Skills insertados correctamente sin duplicados.');
    }
}
